branches:
  only:
    - master
arch:
  - arm64
  - ppc64le
  - s390x
dist: bionic
language: node_js
before_install: |
  NODEJS_VERSION=$(node --version)
  if [ 'v10' = ${NODEJS_VERSION%%.*} ]
  then
    npm install --global npm@7
  else
    npm install --global npm@8
  fi
script:
  - npm run --ignore-scripts build
  - |
    if [ 'v10' = "${NODEJS_VERSION%%.*}" ]; then
      npm run-script test:v8:ci
    else
      npm run-script test:ci
    fi
node_js:
  - 10
  - 12
  - 14
  - 16
  - 17
